name: Create Pull Request on New Branch

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          base: main
          title: 'Automated PR for ${{ github.ref }}'
          body: 'This PR was automatically created by a GitHub Action when a new branch was pushed.'
          draft: false  # Set to true to default PR to draft
